package bot;

public class Constants {
	public final static String 			/*command*/
	NEW_GAME_CMD_NAME         = "new"         ,
	JOIN_CMD_NAME             = "join"        ,
	LEAVE_CMD_NAME            = "leave"       ,
	STARTGAME_CMD_NAME        = "startgame"   ,
	CALL_IKB_CMD_NAME         = "kb"          ,
	LIST_HAND_CMD_NAME        = "list"        ,
	VIEW_HISTORY_CMD_NAME     = "history"     ,
	INITIATE_SKIP_CMD_NAME    = "skip"        ,
	SETTING_CMD_NAME          = "settings"    ,
	SET_GROUP_LINK_CMD_NAME   = "setgrouplink",
	STOP_GAME_CMD_NAME        = "stop"        ,
	ABOUT_CMD_NAME            = "about"       ,
	DEBUG_GAME_CMD_NAME       = "g"           ,
	DEBUG_PLAY_CMD_NAME       = "p"           ,
	DEBUG_REPLY_KEYBOARD_REMOVE = "rkr"       ;
	
	public static final String
	CBQD_SELECT_CARD = "select"     ,
	CBQD_BLANK       = "blank"      ,
	CBQD_PLAY_CARD   = "play"       ,
	CBQD_PASS        = "pass"       ,
	CBQD_UNSELECTALL = "unselectall",
	CBQD_VOTE_SKIP   = "skip"       ,
	
	CBQD_SET_PREFIX             = "set"         ,
	CBQD_VIEW_PREFIX            = "view"        ,
	CBQD_NCARD_10               = "10"          ,
	CBQD_NCARD_13               = "13"          ,
	CBQD_TRUE                   = "true"        ,
	CBQD_FALSE                  = "false"       ,
	CBQD_RANKING_FIRST          = "rf"          ,
	CBQD_SUIT_FIRST             = "sf"          ,
	CBQD_CARD_FIRST             = "cf"          ,
	CBQD_CUSTOM                 = "custom"      ,
	CBQD_SF                     = "sf"          ,
	CBQD_FS                     = "fs"          ,
	CBQD_SVC_BEGIN              = "svc_begin"   ,
	CBQD_SVC_END                = "svc_end"     ,
	CBQD_SETTINGS               = "settings"    ,
	CBQD_GAMERULES              = "gamerules"   ,
	CBQD_LANGUAGE               = "language"    ,
	CBQD_SAVE                   = "save"        ,
	CBQD_NCARD                  = "ncard"       ,
	CBQD_ALLOW_TRIPLE           = "allow_triple",
	CBQD_SV                     = "sv"          ,
	CBQD_CCTC                   = "cctc"        ,
	CBQD_SC                     = "sc"          ,
	CBQD_SCC                    = "scc"         ,
	CBQD_FC                     = "fc"          ,
	
	CBQD_SET_SETTINGS           = CBQD_SET_PREFIX + " " + CBQD_SETTINGS                       ,
	CBQD_SET_GAMERULES          = CBQD_SET_PREFIX + " " + CBQD_GAMERULES                      ,
	CBQD_SET_LANGUAGE           = CBQD_SET_PREFIX + " " + CBQD_LANGUAGE                       ,
	CBQD_SET_NCARD              = CBQD_SET_PREFIX + " " + CBQD_NCARD                          ,
	CBQD_SET_NCARD_10           = CBQD_SET_PREFIX + " " + CBQD_NCARD + " " + CBQD_NCARD_10    ,
	CBQD_SET_NCARD_13           = CBQD_SET_PREFIX + " " + CBQD_NCARD + " " + CBQD_NCARD_13    ,
	CBQD_SET_ALLOW_TRIPLE       = CBQD_SET_PREFIX + " " + CBQD_ALLOW_TRIPLE                   ,
	CBQD_SET_ALLOW_TRIPLE_TRUE  = CBQD_SET_PREFIX + " " + CBQD_ALLOW_TRIPLE + " " + CBQD_TRUE ,
	CBQD_SET_ALLOW_TRIPLE_FALSE = CBQD_SET_PREFIX + " " + CBQD_ALLOW_TRIPLE + " " + CBQD_FALSE,
	CBQD_SET_SV                 = CBQD_SET_PREFIX + " " + CBQD_SV                             ,
	CBQD_SET_SVC_BEGIN          = CBQD_SET_PREFIX + " " + CBQD_SV + " " + CBQD_SVC_BEGIN      ,
	CBQD_SET_SVC_END            = CBQD_SET_PREFIX + " " + CBQD_SV + " " + CBQD_SVC_END        ,
	CBQD_SET_CCTC               = CBQD_SET_PREFIX + " " + CBQD_CCTC                           ,
	CBQD_SET_SF                 = CBQD_SET_PREFIX + " " + CBQD_CCTC + " " + CBQD_SF           ,
	CBQD_SET_FS                 = CBQD_SET_PREFIX + " " + CBQD_CCTC + " " + CBQD_FS           ,
	CBQD_SET_SC                 = CBQD_SET_PREFIX + " " + CBQD_SC                             ,
	CBQD_SET_SC_RANKING_FIRST   = CBQD_SET_PREFIX + " " + CBQD_SC + " " + CBQD_RANKING_FIRST  ,
	CBQD_SET_SC_CUSTOM          = CBQD_SET_PREFIX + " " + CBQD_SC + " " + CBQD_CUSTOM         ,
	CBQD_SET_SCC                = CBQD_SET_PREFIX + " " + CBQD_SCC                            ,
	CBQD_SET_FC                 = CBQD_SET_PREFIX + " " + CBQD_FC                             ,
	CBQD_SET_FC_SUIT_FIRST      = CBQD_SET_PREFIX + " " + CBQD_FC + " " + CBQD_SUIT_FIRST     ,
	CBQD_SET_FC_CARD_FIRST      = CBQD_SET_PREFIX + " " + CBQD_FC + " " + CBQD_CARD_FIRST     ,
	CBQD_SET_FC_RANKING_FIRST   = CBQD_SET_PREFIX + " " + CBQD_FC + " " + CBQD_RANKING_FIRST  ,
	
	CBQD_VIEW_SETTINGS          = CBQD_VIEW_PREFIX + " " + CBQD_SETTINGS                      ,
	CBQD_VIEW_GAMERULES         = CBQD_VIEW_PREFIX + " " + CBQD_GAMERULES                     ,
	CBQD_VIEW_NCARD             = CBQD_VIEW_PREFIX + " " + CBQD_NCARD                         ,
	CBQD_VIEW_ALLOW_TRIPLE      = CBQD_VIEW_PREFIX + " " + CBQD_ALLOW_TRIPLE                  ,
	CBQD_VIEW_SV                = CBQD_VIEW_PREFIX + " " + CBQD_SV                            ,
	CBQD_VIEW_CCTC              = CBQD_VIEW_PREFIX + " " + CBQD_CCTC                          ,
	CBQD_VIEW_SC                = CBQD_VIEW_PREFIX + " " + CBQD_SC                            ,
	CBQD_VIEW_FC                = CBQD_VIEW_PREFIX + " " + CBQD_FC                            ,
	CBQD_MEANINGLESS_RESPONSE   = ".";
	
	
	public static final String
	MSGTXT_PASS = "\u23E9",
	MSGTXT_PLAY = "\u25B6";
}
